### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Gh0stBlade** [zeroKilo/XEXLoaderWV#1]
I followed the video tutorial and couldn't get the .xex file from two Xbox 360 games to load. Does it require a specific type of .xex? i.e unencrypted uncompressed? More info should be provided.

**Comment by Gh0stBlade** [comment]
I tried encrypted and compressed xex
I tried unencrypted and uncompressed xex

No luck, Ghidra tires to load the xex as raw binary.

**Comment by zeroKilo** [comment]
as someone in that video commented: have you install jdk12? its compiled for that

**Comment by Gh0stBlade** [comment]
Thanks, that was the problem. Ghidra FAQ does state that all plugins should be JDK11 though.
