### ISSUE TITLE
Invalid position 

### ISSUE THREAD

**Issue by Mte90** [zeroKilo/XEXLoaderWV#11]
I am testing it with The Saboteur game, using the latest version of ghidra and this plugin.

![Screenshot_20201228_172030](https://user-images.githubusercontent.com/403283/103228415-12a59a00-4931-11eb-80bf-726f66f33164.png)

**Comment by zeroKilo** [comment]
have you selected in options if its retail or devkit version? (we dont know how to detect it, its an encryption issue)
it seems you try to run this on linux but its made for windows, even if ghidra is crossplattform, the plugin is not, it uses a small C# tool to decompress the LZX blocks, I havent found a good java lib for that yet, suggestions are welcome :)

**Comment by Mte90** [comment]
I left devkit flagged as the youtube video doesn't have that flag and the readme is not so clear.
Now I am trying again with unflagged and it is working.

Anyway in linux it is working and is extracting things. I saw the lxzdecomp tool but is in c++ maybe I can help on compile it also for linux.

**Comment by zeroKilo** [comment]
oh yeah, I wrote it in C++ to not need the entire .net framework, its been a while^^ and yes, it CAN work under linux if the xex is only encrypted but not compressed. well thanks for using my software anyway :D

**Comment by Mte90** [comment]
ok I was able to compile it, I will do a pr :-)

**Comment by Mte90** [comment]
pr with linux version of the tool already compiled https://github.com/zeroKilo/XEXLoaderWV/pull/12 I don't know java but I guess that the plugin need to call the right executable.

**Comment by r3sus** [comment]
> have you selected in options if its retail or devkit version? (we dont know how to detect it, its an encryption issue)

iiuc, xex1tool writes if devkit (from https://github.com/emoose/idaxex/releases)

**Comment by zeroKilo** [comment]
added autoloading as in, it tries to first load it as devkit, then as retail before failing, so this shouldnt be an issue in future anymore

**Comment by Mte90** [comment]
Cool!
Just require a new release so I can test it :-D

**Comment by zeroKilo** [comment]
already updated the release, just download again for 9.2.1
