### ISSUE TITLE
Cannot load PDB information.

### ISSUE THREAD

**Issue by NefariousTechSupport** [zeroKilo/XEXLoaderWV#14]
Trying to load default.xex from a skylanders spyro's adventure dev build and sideload pdb info, same way as the 2nd video tutorial.

This XEX is:
```
Devkit
Uncompressed
Encrypted
Title Module
Uses Game Voice Channel 
```

meanwhile the one from #13 is as so:
```
Devkit
Compressed
Encrypted
Title Module
Uses Game Voice Channel
PII
```

Not sure what the issue is, compressing it with xextool didn't help, anyways [here](https://mega.nz/file/jSIlBCJb#5XnUXIetcydIYAZYIbFNHAGhU3QYq4sTTbbpN8zUUAY) are the xex and pdb files for the game, yes I've tried both

**Comment by zeroKilo** [comment]
Im busy this week, but will take a look as soon as I can
greetz WV
