### ISSUE TITLE
10.0.4 update

### ISSUE THREAD

**Issue by oSerenity** [zeroKilo/XEXLoaderWV#15]
can you update it to the current version please?

**Comment by zeroKilo** [comment]
oh, thanks for notefying me :) yes, im going to update all 3 extensions I have asap, but im busy today, I guess I get it done by tomorrow. have a nice day

**Comment by oSerenity** [comment]
ok thanks i appreciate it

**Comment by zeroKilo** [comment]
https://github.com/zeroKilo/XEXLoaderWV/releases/tag/10.0.4 there you go, have a nice day

**Comment by zeroKilo** [comment]
and today they released 10.1. well, great...  so heres also: https://github.com/zeroKilo/XEXLoaderWV/releases/tag/10.1

greetz WV

**Comment by oSerenity** [comment]
thanks

**Comment by Margen67** [comment]
Can you update this to 10.1.2?

**Comment by zeroKilo** [comment]
https://github.com/zeroKilo/XEXLoaderWV/releases/tag/10.1.2
there you go

**Comment by Margen67** [comment]
> [`10.1.2` (release)](https://github.com/zeroKilo/XEXLoaderWV/releases/tag/10.1.2) there you go

What about 10.1.3?

**Comment by zeroKilo** [comment]
will update tomorrow :) keep reminding me +1

**Comment by zeroKilo** [comment]
will do at the weekend, thanks for reminding^^

**Comment by zeroKilo** [comment]
alright, done! have fun^^

**Comment by Margen67** [comment]
10.1.5 was released ~2 weeks ago

**Comment by zeroKilo** [comment]
aaand done! thanks for reminding me :)

**Comment by Margen67** [comment]
> aaand done! thanks for reminding me :)

@zeroKilo I get an error when trying to install it:
![image](https://user-images.githubusercontent.com/3462541/184566886-e5a6358e-6fc1-4e88-99bc-cc9b57911517.png)

**Comment by zeroKilo** [comment]
hmm, seems something messed up there, I will try again, im sorry :)

**Comment by zeroKilo** [comment]
alright, seems I recompiled everything, but didnt updated ghidra... well try again now :)

**Comment by Margen67** [comment]
> alright, seems I recompiled everything, but didnt updated ghidra... well try again now :)

It's working now. Thanks :1

**Comment by Margen67** [comment]
10.2.2 was released a little while ago.

**Comment by zeroKilo** [comment]
already released an update this time :P but thanks for reminding me

**Comment by Margen67** [comment]
10.2.3 got released.

**Comment by zeroKilo** [comment]
thx for reminding, will update as soon as I find time :)

**Comment by zeroKilo** [comment]
@Margen67 made a new release, cheers^^

**Comment by Margen67** [comment]
11.0.3 got released.

**Comment by zeroKilo** [comment]
sorry for the late reply, updated it to 11.1.1 :)
