### ISSUE TITLE
Apply xexp/title update

### ISSUE THREAD

**Issue by Margen67** [zeroKilo/XEXLoaderWV#17]
It would be nice to have a feature that applies an xexp automatically instead of having to use xextool.

**Comment by zeroKilo** [comment]
first time I hear about these, do you have example files? or is there a format description somewhere?

greetz WV

**Comment by Margen67** [comment]
> first time I hear about these, do you have example files? or is there a format description somewhere?
> 
> greetz WV

Do you have Discord?

**Comment by zeroKilo** [comment]
just check any of my recent videos on yt (just google warranty voider) they should all have links to my discord server

**Comment by oSerenity** [comment]
he is talking about updating said xex so you can view it in ghidra for quicker access to debugging or reversing maybe if possible adding a gui that will ask for said xex and xexp and update the binary to be able to see new updated file
example: https://github.com/XboxChef/XexToolGUI

**Comment by zeroKilo** [comment]
after long research, here the first experimental implementation:
![image](https://user-images.githubusercontent.com/12677118/195324293-7ea30049-a8a0-4d7d-b480-a1dc6e39e430.png)
as I only had one file + patch for testing I leave this open for now, happy testing

greetz WV

**Comment by zeroKilo** [comment]
hopefully solved with this commit:

https://github.com/zeroKilo/XEXLoaderWV/commit/29a7a5622e8bdbc5e4489d9e96b77eaf47e53509

please give it a test :)

greetz WV

**Comment by Margen67** [comment]
It's working now, cheers
