### ISSUE TITLE
Some functions show `ord_` instead of function name

### ISSUE THREAD

**Issue by illusion0001** [zeroKilo/XEXLoaderWV#18]
For instnace `XGetVideoMode`.
Import log from xenia `8200061C 826B40BC 3D1 ( 977)    XGetVideoMode`
![image](https://user-images.githubusercontent.com/37698908/187756707-b024033a-fabd-4f6e-bbf8-b3eeaf4fd762.png)

**Comment by zeroKilo** [comment]
https://github.com/zeroKilo/XEXLoaderWV/blob/master/XEXLoaderWV/src/main/java/xexloaderwv/ImportRenamer.java#L936

well it should find this, do you have an example xex for me to test?

greetz WV

**Comment by illusion0001** [comment]
[underworld.zip](https://github.com/zeroKilo/XEXLoaderWV/files/9464513/underworld.zip)

**Comment by illusion0001** [comment]
Only analyze setting I changed is `Non Returning Functions - Discovered` to off to workaround flow override for function calls throughout every xex

**Comment by zeroKilo** [comment]
Alright, well its midnight here, so im gonna check that tomorrow, pls be patient :)

**Comment by zeroKilo** [comment]
Sorry, I had a busy day and wasnt able to check it today, I hope I can find time tomorrow, greetz

**Comment by zeroKilo** [comment]
![image](https://user-images.githubusercontent.com/12677118/188139902-47ad3579-a19f-4ced-a266-4c5ba874eaa6.png)
ok, you found a bug! thanks alot :D got it working now

fix will be uploaded soon^^

**Comment by zeroKilo** [comment]
here is the commit:
https://github.com/zeroKilo/XEXLoaderWV/commit/d8fec56116d7f443ea160e75c7ce0e4ad95e08f3

and I updated the current release:
https://github.com/zeroKilo/XEXLoaderWV/releases/tag/10.1.5

have fun :) greetz WV

PS: please close this ticket if it works for you, thx

**Comment by illusion0001** [comment]
Confirmed fixed
