### ISSUE TITLE
The loadpdb functionality is somewhat broken

### ISSUE THREAD

**Issue by guccigang420** [zeroKilo/XEXLoaderWV#19]
The load pdb functionality does not load datatypes or the function names properly for the .xex executable.

**Comment by guccigang420** [comment]
Apologies for not uploading any images. In the example below you could see that the parameter is undefined, and the names of the functions contain ??@UAAXZ etc
![image](https://user-images.githubusercontent.com/44866346/197237447-b68fa2ab-444c-452d-924e-d98870f59811.png)

This is the example of a struct from the same pdb file loaded in IDA.
![image](https://user-images.githubusercontent.com/44866346/197237804-3d7d64f3-f71e-4c61-9cb0-10e9b731df60.png)

Here also data structure/type info should be present. Also the names of "PTR_Function_.... should be available.
![image](https://user-images.githubusercontent.com/44866346/197238450-97ee8620-3d11-40e0-8e22-57ca70d429ba.png)

**Comment by guccigang420** [comment]
@zeroKilo 
The files to reproduce this: https://mega.nz/file/TF4iFRQT#r0gjCN6AgGGpNvc7Q0l40e9HFj71D3YU8WR5H-dPFRU

**Comment by zeroKilo** [comment]
ok I will take a look, this can take a while, pls be patient or find me on discord if you wanna chat in the meantime. greetz

**Comment by guccigang420** [comment]
Could you post your discord id here?

**Comment by zeroKilo** [comment]
its under every recent yt vid of mine... wv#9312

**Comment by zeroKilo** [comment]
about demangling, I found this, maybe it solves the mangled name problem already:

https://github.com/NationalSecurityAgency/ghidra/issues/1103

PDB support for types is coming, but dont expect too much, documentation for both PDBs and Ghidra are very hard to come by

**Comment by guccigang420** [comment]
Understandable. Hopefully you manage to make it with the types. It's pretty tricky because you have to represent CPP classes as C-Structs with v-tables

**Comment by zeroKilo** [comment]
result: https://github.com/zeroKilo/XEXLoaderWV/commit/754cca3daf48c5bdc61cfff88734d660561b10a0

well I dont have more time to spend on this, that commit and current release are as good as it gets:

- there is now an option to load a pdb in general, it will open a dialog where you can choose between ghidras builtin parser and m$'s DIA parser (essentially using pdb.exe to produce a xml and parse that)
- theres also an option to use my experimental loader (ignoring the choice in the dialog), which is not complete, but im happy to take in outside help :) 

essentially my code can read pretty much every typerecord from the pdb, but the code to apply/import it into ghidra is as best a hack of mine, it needs serious improvement, starting here: https://github.com/zeroKilo/XEXLoaderWV/blob/master/XEXLoaderWV/src/main/java/xexloaderwv/TPIStream.java#L141

greetz

**Comment by mirh** [comment]
https://github.com/NationalSecurityAgency/ghidra/pull/1433 maybe?
