### ISSUE TITLE
Loader sets wrong PPC language by default

### ISSUE THREAD

**Issue by Goatman13** [zeroKilo/XEXLoaderWV#22]
By default loader select **"PowerPC:BE:64:VLE-32addr", "default"**
https://github.com/zeroKilo/XEXLoaderWV/blob/4ecd656db0a0fa30976abd3693c5e606c5985edd/XEXLoaderWV/src/main/java/xexloaderwv/XEXLoaderWVLoader.java#L42

As far as i know Xenon is not VLE processor and support only fixed length opcodes (4 bytes). Due to wrong processor type,  Altivec support is missing. Correct selection should be: **"PowerPC:BE:64:A2ALT-32addr", "default"** . Otherwise, there is no way to decompile/disassemble code like in screenshot:
![image](https://github.com/zeroKilo/XEXLoaderWV/assets/101417270/dd680420-11cb-481b-94bb-1aa69e015edf)

Of course, Ghidra still fail to recognize VMX128 specific instructions, but that require additional work on language files.

**Comment by zeroKilo** [comment]
https://github.com/zeroKilo/XEXLoaderWV/commit/73ab820b4ff29fced75e9f7460d89e680356743e
https://github.com/zeroKilo/XEXLoaderWV/releases/tag/11.0.1 created a new commit and release for this :)

**Comment by Goatman13** [comment]
Thanks! Everything beside VMX128 works as intended now.
