### ISSUE TITLE
Upgrade to Ghidra 11.0.3

### ISSUE THREAD

**Issue by BJNFNE** [zeroKilo/XEXLoaderWV#24]
Would it be possible that you upgrade the Plugin to the latest version of Ghidra (11.0.3)?

**Comment by zeroKilo** [comment]
sorry, did not notice this. just made a release for 11.1.1 that you can use instead

**Comment by BJNFNE** [comment]
Thank you :) it works without any Problems now

**Comment by Margen67** [comment]
#15
Ghidra 11.1.2 was released.

**Comment by zeroKilo** [comment]
ok done :)
