### ISSUE TITLE
Imports not working

### ISSUE THREAD

**Issue by GoobyCorp** [zeroKilo/XEXLoaderWV#5]
Not sure if this is a common issue but Ghidra isn't finding any imports in a module I'm reversing. Am I doing something wrong?

**Comment by zeroKilo** [comment]
no, I actually havent added automatic renaming to the loader, I will think about how to implement that, but currently dont have much time. But for the meantime you could look them up from my renamer script for ida pro https://www.unknowncheats.me/forum/xbox/241978-x360-kernel-function-renamer-script-ida.html
greetz WV
PS: just made a release for ghidra 9.1.2 if you wanna check it out :)

**Comment by zeroKilo** [comment]
sorry for the long delay, but I finally got around fixing this bug. here the update (ghidra 9.1.2)

https://github.com/zeroKilo/XEXLoaderWV/commit/9dd115333191dc20faa30bd9aba1b7359f83cf12

greetz WV

PS: will make new release too
