### ISSUE TITLE
Can't load xex

### ISSUE THREAD

**Issue by iOrange** [zeroKilo/XEXLoaderWV#6]
Hi!
I think I need some input, sorry about that.
No matter what I do, what kind of XEX I'm trying to import - I always end up seeing only "Raw Binary" as the only available format.

The plugin is installed. I just don't understand why it's not working.

Tried on Ghidra 9.0.4 and 9.1.2  (both with appropriate plugin versions).

**Comment by zeroKilo** [comment]
are you sure that its also activated?
https://github.com/zeroKilo/XEXLoaderWV/blob/master/XEXLoaderWV/src/main/java/xexloaderwv/XEXLoaderWVLoader.java#L30
all it checks are the first 4 bytes, do those match?

**Comment by iOrange** [comment]
> are you sure that its also activated?

How do I check for that?
It has a check mark in plugins window. I also restarted Ghidra after it's installation.

Default.xex I have has  "XEX2" as the first 4 bytes.

**Comment by zeroKilo** [comment]
Ok, what JDK version do you use? I think I used JDK 13. Also have you tried compiling from source?

**Comment by LoveMHz** [comment]
Just to add. The release version did not work me, but it did work after compiling from source.

**Comment by mc-17** [comment]
Yep - I also had to recompile to get it to work. Might as well remove that release.

**Comment by zeroKilo** [comment]
I tested the other jdks, they all work fine for me, I even made a new release 2 weeks ago, tested on a new machine, works. so if you guys can recompile it and use it, please report some kind of error message that I can investigate, otherwise this isnt an issue for my code

**Comment by mc-17** [comment]
> I tested the other jdks, they all work fine for me, I even made a new release 2 weeks ago, tested on a new machine, works. so if you guys can recompile it and use it, please report some kind of error message that I can investigate, otherwise this isnt an issue for my code

Apologies, I hope my comment didn’t come off as harsh. 

There is no error, it just silently fails. I’ll look into it more in the coming weeks - for reference I compiled with the newest OpenJDK

**Comment by zeroKilo** [comment]
its fine... `OpenJDK` I havent thought about that, I use regular JDK from oracle, maybe its simply I license issue that the code doesnt want to run. I could try to make releases for both in future
