### ISSUE TITLE
Ghidra 9.2 Support

### ISSUE THREAD

**Issue by r3sus** [zeroKilo/XEXLoaderWV#8]
Hello and thanks a lot for your work!

Could you please add Ghidra 9.2 support?

Thanks.

**Comment by zeroKilo** [comment]
Well I dont find any official release of it yet, as the code can still change alot before its released, I rather wait for that. this tool is open source tho, you could compile it together with your ghidra version if you like.

greetz

**Comment by r3sus** [comment]
Okay, thanks

But even now, analysis goes way faster, than in 9.1.2

There's some repo with compiled ghidra 9.2 if you've interest

https://github.com/garyttierney/ghidra-batteries-included

Thank you

**Comment by GoobyCorp** [comment]
Sorry to resurrect this but will there be a 10.0.1 release of this?

**Comment by zeroKilo** [comment]
now there is, have fun

**Comment by Margen67** [comment]
#15
