### ISSUE TITLE
Index 61440 out of bounds for length 61440

### ISSUE THREAD

**Issue by bbzlazer** [zeroKilo/XEXLoaderWV#9]
Having trouble with the XEX loader

Ghidra 9.0.4
Java 15.0.1
Full exception: https://hastebin.com/awejemuwud
Minecraft Xbox 360 Trial version

**Comment by bbzlazer** [comment]
Others say recompiling the loader helped them but i don't know how

**Comment by zeroKilo** [comment]
well XEX2 would be the correct header, but maybe its XEX1 actually, try this:

https://github.com/zeroKilo/XEXLoaderWV/blob/master/XEXLoaderWV/src/main/java/xexloaderwv/XEXHeader.java#L99

here replace the key with A26C10F71FD935E98B99922CE9321572 and see if that helps, if so, I will add support for that

**Comment by zeroKilo** [comment]
well unless you post a xex file, im going to close this issue soon. I cant debug an error that I can not reproduce
